### ISSUE TITLE
building  environment

### ISSUE THREAD

**Issue by SherlockHolmes221** [tfzhou/C-HOI#4]
I got some errors when building the environment

FAILED: /home/xian/Documents/code/C-HOI/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o
c++ -MMD -MF /home/xian/Documents/code/C-HOI/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /home/xian/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.2/include -I/home/xian/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp -o /home/xian/Documents/code/C-HOI/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ?Wstrict-prototypes?is valid for C/ObjC but not for C++
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp: In function t::Tensor nms(const at::Tensor&, float)鈥?
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: t::DeprecatedTypeProperties& at::Tensor::type() const鈥?is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro HECK_CUDA?
   CHECK_CUDA(dets);
   ^
In file included from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp:2:
/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp:4:80: error: T_CHECK?was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                                                                ^
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro HECK_CUDA?
   CHECK_CUDA(dets);
   ^
[2/2] /usr/local/cuda-9.2/bin/nvcc -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.2/include -I/home/xian/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_kernel.cu -o /home/xian/Documents/code/C-HOI/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_kernel.cu: In function t::Tensor nms_cuda(at::Tensor, float)?
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_kernel.cu:72:62: warning: t::DeprecatedTypeProperties& at::Tensor::type() const?is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   AT_ASSERTM(boxes.type().is_cuda(), "boxes must be a CUDA tensor");
                                                              ^
/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:1: note: declared here
   DeprecatedTypeProperties & type() const {
 ^
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_kernel.cu:81:50: warning: * at::Tensor::data() const [with T = float]?is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   scalar_t* boxes_dev = boxes_sorted.data<scalar_t>();
                                                  ^
/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:341:1: note: declared here
   T * data() const {
 ^
/home/xian/Documents/code/C-HOI/mmdet/ops/nms/src/nms_kernel.cu:109:39: warning: * at::Tensor::data() const [with T = long int]?is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   int64_t* keep_out = keep.data<int64_t>();
                                       ^
/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:341:1: note: declared here
   T * data() const {
 ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 196, in <module>
    zip_safe=False)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/xian/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

How can I solve it?

**Comment by BhandarkarPawan** [comment]
@SherlockHolmes221 I am facing the same error. Did you solve this?

**Comment by SherlockHolmes221** [comment]
> @SherlockHolmes221 I am facing the same error. Did you solve this?

Not yet

**Comment by BhandarkarPawan** [comment]
@SherlockHolmes221 I was able to solve this by updating my CUDA to 9.2 (and installing torch 1.4)

**Comment by SherlockHolmes221** [comment]
> @SherlockHolmes221 I was able to solve this by updating my CUDA to 9.2 (and installing torch 1.4)

Thanks!
